apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pqk0ownfj-go 
  janus-idp.io/tekton: pqk0ownfj-go
  backstage.io/kubernetes-id: pqk0ownfj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pqk0ownfj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  