apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pqk0ownfj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pqk0ownfj-go 
  name: pqk0ownfj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pqk0ownfj-go 
